### ISSUE TITLE
Add to the documentation how to pass parameters to the view

### ISSUE THREAD

**Issue by emanuelet** [fnobi/php-express#12]
I spent quite some time to get it to work.

For who is wondering how to do it

``` javascript
    return res.render("index.php", {
            get: {
                slug: slug
            }
        });
```

same thing for a POST request

**Comment by Chickenchaser-Kwak** [comment]
You saved my life. Thanks :-)

**Comment by multianimus** [comment]
Wow thanks for this. I spent like 2 days on the issue before I found this post. Thank you. Still can't get post to work, but get should be good enough.
